apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'smtp.sjhz.cf:25'
      smtp_from: 'a@sjhz.cf'
      smtp_auth_username: 'a@sjhz.cf'
      smtp_auth_password: 'Vwv56ty7'
      smtp_require_tls: false
    templates:    # 增加templates配置，指定模板文件
      - '/etc/alertmanager/template_email.tmpl'
    route:
      group_by: [alertname]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10m
      receiver: default-receiver
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'b@sjhz.cf'
        send_resolved: true
        #message: '{{ template "email.html" . }}'
        html: '{{ template "email.html" . }}'    # 此处通过html指定模板文件中定义的email.html模板
  template_email.tmpl: |-
    {{ define "email.html" }}           # 此处的email.html 必须和上面指定的一致（此行注释不可以写进template模板文件中）
    {{- if gt (len .Alerts.Firing) 0 -}}{{ range .Alerts }}
    @警报<br>
    实例: {{ .Labels.instance }}<br>
    信息: {{ .Annotations.summary }}<br>
    详情: {{ .Annotations.description }}<br>
    时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}<br>
    {{ end }}{{ end -}}<br>
    {{- if gt (len .Alerts.Resolved) 0 -}}{{ range .Alerts }}<br>
    @恢复<br>
    实例: {{ .Labels.instance }}<br>
    信息: {{ .Annotations.summary }}<br>
    时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}<br>
    恢复: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}<br>
    {{ end }}{{ end -}}
    {{- end }}
type: Opaque
