apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'smtp.sjhz.cf:25'
      smtp_from: 'a@sjhz.cf'
      smtp_auth_username: 'a@sjhz.cf'
      smtp_auth_password: 'Vwv56ty7'
      smtp_require_tls: false
    templates:    
      - '/etc/alertmanager/template_email.tmpl'
    route:
      group_by: [alertname]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10m
      receiver: default-receiver
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'b@sjhz.cf'
        send_resolved: true
        #message: '{{ template "email.html" . }}'
        html: '{{ template "email.html" . }}' 
  template_email.tmpl: |-
    {{ define "email.html" }} 
    {{- if gt (len .Alerts.Firing) 0 -}}{{ range .Alerts }}
    @Alert<br>
    instance: {{ .Labels.instance }}<br>
    info: {{ .Annotations.summary }}<br>
    description: {{ .Annotations.description }}<br>
    timestamp: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}<br>
    {{ end }}{{ end -}}<br>
    {{- if gt (len .Alerts.Resolved) 0 -}}{{ range .Alerts }}<br>
    @recovery<br>
    instance: {{ .Labels.instance }}<br>
    info: {{ .Annotations.summary }}<br>
    timestamp: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}<br>
    recovery: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}<br>
    {{ end }}{{ end -}}
    {{- end }}
type: Opaque
