apiVersion: pxc.percona.com/v1-9-0
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
    - delete-pxc-pods-in-order
spec:
  crVersion: 1.9.0
  secretsName: my-cluster-secrets
  vaultSecretName: keyring-secret-vault
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal
  logCollectorSecretName: my-log-collector-secrets
  allowUnsafeConfigurations: false
  updateStrategy: Never
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: 8.0-recommended
    schedule: "0 4 * * *"
# use pxc 5.7.33
  pxc:
    size: 3
#    image: percona/percona-xtradb-cluster:8.0.23-14.1
    image: percona/percona-xtradb-cluster:5.7.33-31.49
    autoRecovery: true
    resources:
      requests:
        memory: 1G
        cpu: 600m
    nodeSelector:
      service_type: pxc
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
#      emptyDir: {}
      hostPath:
        path: /data/pxc
        type: Directory
#      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
#        resources:
#          requests:
#            storage: 2G
    gracePeriod: 600
# use haproxy
  haproxy:
    enabled: true
    size: 3
#    image: percona/percona-xtradb-cluster-operator:1.9.0-haproxy
    image: percona/percona-xtradb-cluster-operator:1.8.0-haproxy
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
# disable proxysql
  proxysql:
    enabled: false
    size: 3
    image: percona/percona-xtradb-cluster-operator:1.9.0-proxysql
    resources:
      requests:
        memory: 1G
        cpu: 600m
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    volumeSpec:
#      emptyDir: {}
#      hostPath:
#        path: /data
#        type: Directory
      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2G
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
# logcollector
  logcollector:
    enabled: true
#    image: percona/percona-xtradb-cluster-operator:1.9.0-logcollector
    image: percona/percona-xtradb-cluster-operator:1.8.0-logcollector
# disable pmm
  pmm:
    enabled: false
    image: percona/pmm-client:2.18.0
    serverHost: monitoring-service
    serverUser: admin
# disable pitr,Point-in-time recovery is supported by the Operator only with Percona XtraDB Cluster versions starting from 8.0.21-12.1
  backup:
#    image: percona/percona-xtradb-cluster-operator:1.9.0-pxc8.0-backup
    image: percona/percona-xtradb-cluster-operator:1.9.0-pxc5.7-backup
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    storages:
#      s3-us-west:
#        type: s3
#        s3:
#          bucket: S3-BACKUP-BUCKET-NAME-HERE
#          credentialsSecret: my-cluster-name-backup-s3
#          region: us-west-2
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            storageClassName: rook-cephfs
            accessModes: [ "ReadWriteMany" ]
            resources:
              requests:
                storage: 6G
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
#        storageName: s3-us-west
        storageName: fs-pvc
      - name: "daily-backup"
        schedule: "0 12,13,14 * * *"
        keep: 5
        storageName: fs-pvc