apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-ingress
  namespace: app-dev
spec:
  ingressClassName: nginx
  rules:
  - host: "dev-vue.juneyaokc.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: vue-nodeport
            port:
              number: 8083
