apiVersion: v1
kind: ConfigMap
metadata:
  name: hwy-configmap-2
data:
  application.properties: |
    env=local
    msg=this is local env properteis.
  mysql.properties: |
    mysql.hostname=127.0.0.1
    mysql.port=3306  
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1zaGFuZ2hhaS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogImRHRnZhWE4wYlc5dWEwQXhOak11WTI5dE9sWjNkalUyZEhrMyIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwy-2
  labels:
    app: hwy-2
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hwy-2
  template:
    metadata:
      labels:
        app: hwy-2
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
      - name: hwy
        image: registry.cn-shanghai.aliyuncs.com/jyjt/develop-demo-spring-a:202109221122
        imagePullPolicy: IfNotPresent
        args: ["--spring.config.location=application.properties,mysql.properties"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: hwy-configmap-2
          mountPath: /opt/application.properties
          subPath: application.properties
        - name: hwy-configmap-2
          mountPath: /opt/mysql.properties 
          subPath: mysql.properties   
      volumes:
      - name: hwy-configmap-2
        configMap:
          name: hwy-configmap-2
          items:
            - key: application.properties
              path: application.properties 
            - key: mysql.properties
              path: mysql.properties  
---
apiVersion: v1
kind: Service
metadata:
  name: hwy-2
  labels:
    app: hwy-2
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hwy-2     
