apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sjhz
spec:
  serviceName: sjhz-service  # create serviceName 
  selector:
    matchLabels:
      name: sjhz
  replicas: 1
  template:
    metadata:
      labels:
        name: sjhz
    spec:
      containers:
      - name: sjhz
        image: sjwayrhz/demo-vue:v1.0
        ports:
        - containerPort: 80
