apiVersion: v1
kind: ConfigMap
metadata:
  name:  api-config
  namespace: app-prod
data:
  api-env: prod
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
  namespace: app-prod
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1zaGFuZ2hhaS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogImRHRnZhWE4wYlc5dWEwQXhOak11WTI5dE9sWjNkalUyZEhrMyIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  api-pvc
  namespace: app-prod
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api
  namespace: app-prod
  labels:
    app:  api
spec:
  selector:
    matchLabels:
      app:  api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  api
    spec:
      imagePullSecrets: 
        - name: registry-pull-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api
              topologyKey: kubernetes.io/hostname
      containers:
        - name:  api
          image: registry.cn-shanghai.aliyuncs.com/jyjt/master-api:202111191652
          imagePullPolicy: IfNotPresent
          args: ["--spring.profiles.active=$(api-env-key)"]
          ports:
          - containerPort: 8081 
          env:
          - name: api-env-key
            valueFrom:
              configMapKeyRef:
                name:  api-config
                key: api-env 
          readinessProbe:
            httpGet:
              path: /swagger-ui.html
              port: 8081
            initialDelaySeconds: 40
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          resources:
            limits:
              cpu: "4"
              memory: "4Gi"
            requests:
              cpu: "3"
              memory: "3Gi" 
          volumeMounts: 
            - name: nfs
              mountPath: /logs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName:  api-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  api-nodeport
  namespace: app-prod
  labels:
    name:  api-nodeport
spec:
  type: NodePort
  ports:
  - name:  api
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app:  api
