apiVersion: v1
kind: Service
metadata:
  name:  api-nodeport
  namespace: app-dev
  labels:
    name:  api-nodeport
spec:
  type: NodePort
  ports:
  - name:  api
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app:  api
