apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  namespace: app-dev
  labels:
    name: web-nodeport
spec:
  type: NodePort
  ports:
  - name: web
    port: 8082
    targetPort: 8082
    nodePort: 30082
  selector:
    app: web
