apiVersion: v1
kind: Service
metadata:
  name: web-clusterip
  namespace: app-dev
  labels:
    name: web-clusterip
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8082
    targetPort: 8082
  selector:
    app: web
