kind: Service
apiVersion: v1
metadata:
  name: redbag-clusterip
  namespace: app-dev
  labels:
    name: redbag-clusterip
spec:
  selector:
    app: redbag
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8084