kind: Service
apiVersion: v1
metadata:
  name: vue-clusterip
  namespace: app-dev
  labels:
    name: vue-clusterip
spec:
  selector:
    app: vue
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083