kind: Service
apiVersion: v1
metadata:
  name: redbag-nodeport
  namespace: app-dev
spec:
  selector:
    app: redbag
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8084
      nodePort: 30084