apiVersion: v1
kind: ConfigMap
metadata:
  name: meet-config
  namespace: app-prod
data:
  meet.conf: |-
    server {
      listen  8085;
      server_name localhost;
      client_max_body_size 800M;
      access_log /var/log/nginx/meet_access_log main;
    
      location / {
        root /usr/share/nginx/html; 
        index index.html;
      }
      
      location /api {

        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;

        proxy_http_version 1.1;
        proxy_set_header Connection ""; 
        
        proxy_pass http://10.220.62.240:30081;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
  namespace: app-prod
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5jbi1zaGFuZ2hhaS5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogImRHRnZhWE4wYlc5dWEwQXhOak11WTI5dE9sWjNkalUyZEhrMyIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meet-pvc
  namespace: app-prod
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
---
kind: Service
apiVersion: v1
metadata:
  name: meet-nodeport
  namespace: app-prod
spec:
  selector:
    app: meet
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8085
      targetPort: 8085
      nodePort: 30085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet
  namespace: app-prod
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: meet
  replicas: 1
  template:
    metadata:
      labels:
        app: meet
    spec:
      imagePullSecrets: 
        - name: registry-pull-secret
      containers:
        - name: meet
          image: registry.cn-shanghai.aliyuncs.com/jyjt/master-meet:v1.0
          readinessProbe:
            httpGet:
              path: /#/login
              port: 8085
            initialDelaySeconds: 3
            failureThreshold: 5
            periodSeconds: 3
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
          - name: http
            containerPort: 8085
          volumeMounts:
          - name: meetconf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
          - name: meetlog
            mountPath: /var/log/nginx/
      volumes:
      - name: meetconf
        configMap:
          name: meet-config
      - name: meetlog
        persistentVolumeClaim:
          claimName: meet-pvc