apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: deployment-helloworld
  namespace: develop-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/jyjt/helloworld:34
        name: helloworld
