apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-single
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      nodePort: 30378
  selector:
    app: redis