apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cluster-pvc
  namespace: app-dev
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20G
