apiVersion: v1
kind: Service
metadata:
  name:  api-clusterip
  namespace: app-prod
  labels:
    name:  api-clusterip
spec:
  type: ClusterIP
  ports:
  - name:  api
    port: 8081
    targetPort: 8081
  selector:
    app:  api
