apiVersion: v1
kind: Service
metadata:
  name: jms-web
  labels:
    app.jumpserver.org/name: jms-web
spec:
  type: NodePort
  ports:
    - name: jms-web
      port: 80
      nodePort: 30180
  selector:
    app.jumpserver.org/name: jms-web