apiVersion: apps/v1
kind: Deployment
metadata:
  name: qfusion-installer
  labels:
    app: qfusion-installer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: qfusion-installer
  template:
    metadata:
      labels:
        app: qfusion-installer
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: qfusion-installer
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.registry }}/{{ .Values.global.repository }}/installer-operator:{{ .Chart.AppVersion }}"
          args:
            - --platInfo={{ .Values.platInfo }}
            - --node-label={{ .Values.nodeLabel }}
            - --oinstaller-img={{ .Values.global.registry }}/{{ .Values.global.repository }}/oracle-installer:{{ .Values.oinstallerVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- with .Values.ext.cmName }}
            - name: extprofiles
              mountPath: /extProfiles
              readOnly: true
            {{- end }}
            - name: timezone
              mountPath: /etc/localtime
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: ""
          name: timezone
     {{- if .Values.ext.cmName }}
        - name: extprofiles
          configMap:
            name: {{ .Values.ext.cmName }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
data:
  timezone: |
    Asia/Shanghai
kind: ConfigMap
metadata:
  name: timezone