apiVersion: qfusion.woqutech.com/v1alpha1
kind: InstallerOperator
metadata:
  name: {{.Release.Name}}
spec:
  cmdbConfig: {}
  deployType: {{ .Values.deployType }}
  esConfig:
    nodeSelector:
      nodeSelectorTerms: null
  globalConfig:
    global:
      registry: {{ .Values.global.registry }}
      repository: {{ .Values.global.repository }}
      dataDir: {{ .Values.global.dataDir }}
      imagePullSecret: {{ .Values.global.imagePullSecret }}
    nodeExporter:
      nodePort: false
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoSchedule
      key: qfusion/master
      operator: Exists
    nodeSelector:
      qfusion/master: "true"
  prepareYaml: |2

    apiVersion: v1
    kind: Namespace
    metadata:
      name: qfusion-admin
      labels:
        name: qfusion-admin
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: dboperator
      namespace: qfusion-admin
      labels:
        app: qfusion-admin-operator
    {{- with .Values.global.imagePullSecret }}
    imagePullSecrets:
      - name: {{ . }}
    {{- end }}
    ---
    apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: ClusterRoleBinding
    metadata:
      name: dboperator-qfusion-admin
      labels:
        app: qfusion-admin-operator
    subjects:
      - kind: ServiceAccount
        name: dboperator
        namespace: qfusion-admin
    roleRef:
      kind: ClusterRole
      name: qfusion-cluster-role
      apiGroup: rbac.authorization.k8s.io
    ---
    apiVersion: v1
    data:
      timezone: |
        Asia/Shanghai
    kind: ConfigMap
    metadata:
      name: timezone
      namespace: qfusion-admin
    ---
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: department-isolation
      namespace: qfusion-admin
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
      ingress:
        - from:
          - namespaceSelector:
              matchExpressions:
                - key: name
                  operator: In
                  values:
                  - {{ .Release.Namespace }}
                  - qfusion-admin
                  - kube-system
          - podSelector:
              matchLabels:
                qfusion.woqutech.com/allowed-namespace: qfusion-admin

  profiles: # 后面的优先级比前面高
  - empty.profile
  {{- with .Values.baseProfiles }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.ext.profiles }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  components:
    webserver:
      nodeExporter:
        nodePort: true