apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: app-prod
spec:
  ingressClassName: nginx
  rules:
  - host: "api.juneyaokc.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: api-clusterip
            port:
              number: 8081
