apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      restartPolicy: Always
      containers:
      - image: docker.sjhz.tk/busybox:1.34.1-glibc
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
        name: busybox
