# 10.225.63.20
apiVersion: v1
kind: Secret
metadata:
  name: rocky-ssh
type: Opaque
data:
  authorized_keys: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDdG1yQmZPRkxGOHRVQnlaTU5iUmtoQ3FyTHhQc2NJMUlBdnYvd2pKdXN0REVzdm40VzBXeHg3VUlzU0doQmJSa0JFM3BNanlOSnlseXFsa0ZpeHQ5b25HVGRTVk1kTnVBeEhTVHFWN241QjRaWFhtdVNUR25sMkRTS1lnT1NsZUNwYWtBSzE1VEJDbFBtMWFCMGMzUmh2c2Q2aXlNZlREOU1LR1hFTml0cG9rVG9PMFhTSk1VL25qcUVraEpjd1hUR0hYenRwaXRxc1ZuWEkvNEJVWXlhNlpZc21LQVNGd2FQbXBqdmpySThWMmVWVFM5YmFqRGg3QXA4WFM5ZDk2TlFZcUNVMkl1dGFZZXFNNy8wUzlWL2FDR2szTStLNXVsVkVwd2I1YnUyZmpkMUdURzBXYURQZHhaMThEYlhCWkVZcDJ3TmdZcHRSeDhEL0FNMzloVFQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: rocky-kubectl
type: Opaque
data:
  config: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VNMWVrTkRRV01yWjBGM1NVSkJaMGxDUVVSQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSYzBaQlJFRldUVkpOZDBWUldVUldVVkZFUlhkd2NtUlhTbXdLWTIwMWJHUkhWbnBOUWpSWVJGUkplRTFVU1hoT1JFRXlUWHBCZVU1R2IxaEVWRTE0VFZSSmVFMXFRVEpOZWtGNVRrWnZkMFpVUlZSTlFrVkhRVEZWUlFwQmVFMUxZVE5XYVZwWVNuVmFXRkpzWTNwRFEwRlRTWGRFVVZsS1MyOWFTV2gyWTA1QlVVVkNRbEZCUkdkblJWQkJSRU5EUVZGdlEyZG5SVUpCVUcxTENrc3JZV0ZVYTFRNFlUSTBjamgxTm1kWWIzTTVVa3B4WWxsVVZTOTRkM1ZsTmt4dmJsaHJZVE50YTNRNFkweEJjVXhqZWsxSFdUWlpkSEpGWTFkVWFUa0tNVnBKTm5KMFJuSjJhSFZwS3prMVlXVmlPVmxsZFdkaE5tcDJORWgwVm5KbFJEUnFUMEpwZEVnMFdGbEVkR2t5Y2tsMmFWbExUVlV6Y1dKa1MxaDJLd3BrT0VsTlQxUkJNeXR2TjNOdFozSkpaVUpEZDBWSVdFdFFZVkZ6TWxwa05FeEdiRE5XZUVoa2RqUnZUMGRQVERGdFJHTnpSakZLUmtoUGNDdDBjbFp1Q2xCellqTmxNVkpGV1hSNGNVWTNaSEJqV1RSRlVuSlljVFJEVVhCc05rTXdVbkZxY0VaNVpWSnFSR2xXSzFGWGJuaDFSRVZCVEhWcE1XUk1UalYzZFZFS2VUQTJZbEpFV213eWR6QmtTa2MyTVVsb1ZYVndRa05CY25aMlkxWktSM0ZvVDBGbVpTOXpUQzgxUVZSeVZtVjRSMVpNVFN0aVpXdFdLMnBCV0V4dll3cHFlRFl4YTJOaGVWVk1MMWxIZVRFd2VYcGpRMEYzUlVGQllVNURUVVZCZDBSbldVUldVakJRUVZGSUwwSkJVVVJCWjB0clRVRTRSMEV4VldSRmQwVkNDaTkzVVVaTlFVMUNRV1k0ZDBoUldVUldVakJQUWtKWlJVWkxWMmhZWm5SRk9IbFlVRmxUYm1KSFVEZDVVbkJyT0VjdlExVk5RVEJIUTFOeFIxTkpZak1LUkZGRlFrTjNWVUZCTkVsQ1FWRkRSM051UTFZMU5VTlVTekp6UWs5SmJ6aG9LM2hJTm10VVNFRmtabGRKZGxKV1NpOUxOVlpZY2tnM1EyeHZNRXBwVVFwME1Ea3pTVUZFYTJJd01FVnBaSEl4YkhFeFNsSk5LMHM1TjNrNVZGcDVSbUp1UVRsR2NqUnpOVVp3ZHpsQ05tdFhSVkZqT0cxbGFsZDZObWszTkVKNUNtaEljMDFUZFdWVWFVVjBjblVyWTFSellYTnlUbXA0WVVGbVJGSjJZbXBXV25aNWQzQTRNR054YkhJcmJXWjJNblV5VlVRelJGaFdVekJCUWpka2FrZ0tabGRDTnpOMVJ6aEthSFJ4UVZnclR6WXpVSG8wWTBwNFZGaDJXblV6TTIxQlIyTTRiRkZRUW5jeEwzZEdkMDVuUWpsVVprUjNNRFJ0UVZJeU5ERnlMd3BzZEUxVlJtNDJTVzB6U0c1UFRFcFhhbE5TYnpsNWVIRnpORVJvVGtGdVUxWm9WemdyYWtobU1FTm5XRE5ITVRadlNIWXdXbUp6TTI5UU4yVkRkV3AyQ2t4RFdrMU5OVGRuWlRkWlprdHRPRFV5WW5Kc1RXZ3dkRVIzUVdoaVMyRm5jM2h0UkFvdExTMHRMVVZPUkNCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2c9PQogICAgc2VydmVyOiBodHRwczovLzEwLjIyNS42My4yMDo2NDQzCiAgbmFtZTogY2x1c3Rlci5sb2NhbApjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogY2x1c3Rlci5sb2NhbAogICAgdXNlcjoga3ViZXJuZXRlcy1hZG1pbgogIG5hbWU6IGt1YmVybmV0ZXMtYWRtaW5AY2x1c3Rlci5sb2NhbApjdXJyZW50LWNvbnRleHQ6IGt1YmVybmV0ZXMtYWRtaW5AY2x1c3Rlci5sb2NhbApraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGt1YmVybmV0ZXMtYWRtaW4KICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVVJKVkVORFFXZHRaMEYzU1VKQlowbEpTWGtyWWxsMGRUTk9XakIzUkZGWlNrdHZXa2xvZG1OT1FWRkZURUpSUVhkR1ZFVlVUVUpGUjBFeFZVVUtRWGhOUzJFelZtbGFXRXAxV2xoU2JHTjZRV1ZHZHpCNVRWUkZlVTFVVVhkT2FrMTNUV3BTWVVaM01IbE5ha1Y1VFZSUmQwNXFUWGROYWxaaFRVUlJlQXBHZWtGV1FtZE9Wa0pCYjFSRWJrNDFZek5TYkdKVWNIUlpXRTR3V2xoS2VrMVNhM2RHZDFsRVZsRlJSRVY0UW5Ka1YwcHNZMjAxYkdSSFZucE1WMFpyQ21KWGJIVk5TVWxDU1dwQlRrSm5hM0ZvYTJsSE9YY3dRa0ZSUlVaQlFVOURRVkU0UVUxSlNVSkRaMHREUVZGRlFYSjFVMWh2UkhGaVZXRlFWbWQwYTAwS1UyVnhMMFpGUmtSUVNVdE5Oelp0V2xkdVJVZFBRbTFuTUdsWWR5OVJMMEpYYUVNNFEyazJSR2RoYm1OTWNFdHlSblYzY0ZKcVNDODBhVWxqYW5STk1ncFBjVWt6ZEU1cldFOHhaVFJ6Y1ZKUWJHcHFjVTFFVmpWVlFuVkxURlpFVjBoNVlYbHBjbXMzZUZaWFZtMDVVMDF1U0daTlRGUm9LM0UwWmxOM2VqUmFDalZ4Y0cxU05qTkJUMlZtVGpCNGJIQkdXSFJ3TmxsQ2NuUk5jWGQ1T1ZoTVpIcE9ia3RqVUd4d1ZrNTJRbFZEYzJzMmN5dFBZMlJZVnpoRE1tSkRNeklLZVhOTGFuZEZhRUp2TDB3dk16VlFTbTR5TDNkSUwzazVNMFExT0ZKamJVUTBOR2xPYm0xQ1JIZERUakJEWkV4Nk1XWjZOSEF6UmlzMmNtNU5ZVWRoVUFwalJWZFRZWFpRUW5WV1QydDNkUzlCY3pCWlZEWnFNMVZHTjBVeGMzQlNXRXQzZVRNM2VtZzJhVUpOYkU1amVrNXFlWEpTTURJMVdHcFRhek5EVFdWU0NqazRaSFp0VVVsRVFWRkJRbTh4V1hkV1JFRlBRbWRPVmtoUk9FSkJaamhGUWtGTlEwSmhRWGRGZDFsRVZsSXdiRUpCZDNkRFoxbEpTM2RaUWtKUlZVZ0tRWGRKZDBSQldVUldVakJVUVZGSUwwSkJTWGRCUkVGbVFtZE9Wa2hUVFVWSFJFRlhaMEpUYkc5V016ZFNVRTFzZWpKRmNESjRhaXM0YTJGYVVFSjJkd3BzUkVGT1FtZHJjV2hyYVVjNWR6QkNRVkZ6UmtGQlQwTkJVVVZCZEM4NFJUTnZWVUpRWlRSR1VIVTRWakExUm5JeFJVSnFiMDFZWldGS1NsRnVkMDlFQ2twMVVUZFlUVEpLVEVGdWRYSm5hVkZ5UlVjM2MyeFNTbGxhVUhOSGJGb3hNR2QwWVZsUVJUWXZUWEI1UVZabFZYbE5WMmhCTTFObGFGUXJSalp1ZW0wS2JIa3pkamxoYVhObk5FcE5TbkJwY0RkbE5XeG5WMlIzYTA1dkwzTmFUaTlUVlZVd1lWSTJaMUJWZUhCRlUwNUlWMmhIVVdsTVpXTlFNWEYzYVhaU1NRcDBlbFJOTUd4bFR6azViM1VyWkZoSk1IZEpZa1ZZVDBaSFlpdEpNMDl3VEc5S1VXMVdVMUptWmxseVVrVndOV3BvWVRseVdXRm1NRXA2VEV4aFFTc3ZDbEJTYW1ZeFpXSlhORzV0ZDBoMFdWWk5MMHhMTTB4NlFtMWhTa05OV1U4elRuRjBVR2xSTkU5RE1WbE5hMDVvU1VwM01IUjZkVUl4ZWxGbE5HRTBkbklLUjFNdmRGRkJUMGxOTDBneFZWcFlWV2xXVTBWaVdXTXJOVEZQTUN0NFVXcHFVWHBYTjNvd04ydG9NeXNyVFZsSFFtYzlQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDZz09CiAgICBjbGllbnQta2V5LWRhdGE6IExTMHRMUzFDUlVkSlRpQlNVMEVnVUZKSlZrRlVSU0JMUlZrdExTMHRMUXBOU1VsRmNFRkpRa0ZCUzBOQlVVVkJjblZUV0c5RWNXSlZZVkJXWjNSclRWTmxjUzlHUlVaRVVFbExUVGMyYlZwWGJrVkhUMEp0WnpCcFdIY3ZVUzlDQ2xkb1F6aERhVFpFWjJGdVkweHdTM0pHZFhkd1VtcElMelJwU1dOcWRFMHlUM0ZKTTNST2ExaFBNV1UwYzNGU1VHeHFhbkZOUkZZMVZVSjFTMHhXUkZjS1NIbGhlV2x5YXpkNFZsZFdiVGxUVFc1SVprMU1WR2dyY1RSbVUzZDZORm8xY1hCdFVqWXpRVTlsWms0d2VHeHdSbGgwY0RaWlFuSjBUWEYzZVRsWVRBcGtlazV1UzJOUWJIQldUblpDVlVOemF6WnpLMDlqWkZoWE9FTXlZa016TW5selMycDNSV2hDYnk5TUx6TTFVRXB1TWk5M1NDOTVPVE5FTlRoU1kyMUVDalEwYVU1dWJVSkVkME5PTUVOa1RIb3habm8wY0ROR0t6WnliazFoUjJGUVkwVlhVMkYyVUVKMVZrOXJkM1V2UVhNd1dWUTJhak5WUmpkRk1YTndVbGdLUzNkNU16ZDZhRFpwUWsxc1RtTjZUbXA1Y2xJd01qVllhbE5yTTBOTlpWSTVPR1IyYlZGSlJFRlJRVUpCYjBsQ1FWRkRjRnBWVjNKaWVtbEVUV0pIWVFvMVFXMTNRMjkyTmpOV09UTlhNbVZSZEcwclVHeDNkVlZEVG1Gdk1WSkVLM1V5VkcxcVNFUnNWamR2VDA4cmVrVjFNVU14YVdoYVRVcENLMWs0Y25SQkNscDZhMDlRTlVzdlQzTnVlWE16ZERCd1FYUnRSVVZvWTFjeE4yVkNWalp1YkRkV1pGSk5hMGczYmxGRVNsZHpZMGhTYmpSaU1YY3lja3BMWTBvMWEzWUtaa3BZZG5kcWIwRXdWSHAyYlZOTVZtaGlXWFpzV0VzelRrdHBaREpXTUM5RlZFMXdURTkzTjNVemN6RXlORUo2U1dsVVQxb3hTRW93UzNwelNuaEljd3BpYkRSV1VVUlhhR3hSUmxkSllsQXhMekpMYVhnclNpczFVbmcxUm14WWVrNW1TMVYwVVhkalUyUm5NVTE0VjNvNE0zZHdZM1ZTTDBWNE0zTkJhVlJsQ2xsYU9FVnJjRzhyZUhoR1lTOWtWa0ZJTTNkNlNXbFRaWE13WlZNMmVXdE9UaXRyVkZORmQyVXJNM05MTnpWT00zVXJhbEY0ZFRaaVdsQnNabE5yWVV3S00ycFVUR3hWVWxKQmIwZENRVTlpTUVkSk4yVjFNa05PWjNCVGJIRllSWGRHYTBRM1NERldZWE01TTBoMVdXNW5kR3RqWms1S1IzZzVSbU5XVTBwbE9RcFBjbTlXY2psbmRWazBSME40TlVoT1RHcDZabVpGYkVOMVNtOHpVa1ZTTTNsM01WVlBTaTlHUzBwYVl6aEVha3hWUzJWak5tNTVSaXR0VjFGRE5WcElDbVJRUmpacFFtMDJjVlpoV2pBelVVaHFVVWhaWTA5MVF5dG5kMmsyUVZSNlZtaEJVakZHTW1WUGQwVmtWWFJ3Umt0RlEyOW1lRFpXUVc5SFFrRk5TR01LUjJRNWRqQm5TSEkwZUZGaGFrbE9ka1pOVGpSNVJUVjVOMU54TjBJclJXdG5hekpNZFdOaGVXSlNOVmhCT0ZSSGVFTkJSa3BuTDB4U1ZuaG5NemROTVFwc01rUmtVM1UyVGt4bmFrbzVSbTV0WXpkV0syOVJORlowWld4RVdHWk5XV2hVUzB4SVZ6ZzBRbmR6VmtjMWVrY3ZNMkpYVUROTVJHbHhVQzlZY0RCWUNtUTBiRFkyY0RjNGFGUXpiSEo1WmtSbmExTnZNRmR5VVZWV2QycGlhWG93T1ROQ2JteHlMekZCYjBkQ1FVbDZTblZ1Y2tadWJsbDVZbUZ5VGk5cFptOEtlRE5uWmxoaE9UZHNia0ZhVVRaeFoxZEtNbk5yVkVKTWVXZGhXVU1yVDNOVlJFOUdOblZqWmtORWRUUkVTVFVyUWt4VVNrUkJkbWMxTkZocVRWQlBTUXBFZW1veE5GaHlUVUp1ZWpZNVRtMDJXREZXSzBjMVpVUlhUM2N5ZW10c2VrUXZMM2N3VTNwWFJrVnhaR2hWUTFSS1kzTTVUbFZFYzFoQ0szWXlOemRCQ2pBdlRVSXlNMHRwWkZwbGRGWTBaVVphZHpsaVdpOXhkRUZ2UjBGS2NuUTFSaXRHV21wcVV6VkRMekExT0dSRGVIb3hVa1ZuVW1kS1RuRTFhbkJ4U1VzS2RuSXJZVUZKT0VweGFsRnpaSEJhV0M5VFdFdE5kMGRxTDBFNFJ6UjFSbXRQTWtFM1dtMXZhWFJ1VEZST1ZuTk1OVEJzUkcxSVRGTkJObU5KUlVabWJnb3hUemxwYkVOUldHeERiRVpsVVRsNFdIbGllbE5zVTNwVlNYcHVUa2N2U2pOR1owbHdTR1JFYWpsb2FVcEpiVEZpTURWcVpWQnVhVW8wZVZWeFRISlJDamRWTld4SGFtdERaMWxDTUc1a2FuTXZXbUo2Ylhnd1p6SmxWMGROTTBaeE5VSm9iRFZ6VTFSV1JucFFObTVoYVVsMFJFSlpPVGhFYzNsUlJsVkxXVXNLT0ZWMVdWQnVXREozTUZaNFMwTjNXVmh2TnpSR1JWVnNOSE0xTDFkMWMxVXdlRk5qY1RFNVN6ZGpibmh2SzBOUmJ6QTBVRmxPWkdaYVVYSTFkWEJDZUFweVNscDVaREZoVnl0S1VYWnVSM04wTkhZclpHd3dWV2xIYlVoRk5UQnliMmRzWXpkeVJraG5RemRsUVRKTFUwaEpOR1J1VWtFOVBRb3RMUzB0TFVWT1JDQlNVMEVnVUZKSlZrRlVSU0JMUlZrdExTMHRMUW89
---
apiVersion: v1
kind: Service
metadata:
  name: rocky-ssh-service
  labels:
    name: rocky-ssh
spec:
  type: NodePort
  ports:
    - name: rocky-ssh
      port: 22
      targetPort: 22
      nodePort: 30022
  selector:
    name: rocky-ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocky-ssh
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: rocky-ssh
  template:
    metadata:
      labels:
        name: rocky-ssh
    spec:
      volumes:
        - name: ssh
          secret:
            secretName: rocky-ssh
            defaultMode: 384
        - name: kubectl
          secret:
            secretName: rocky-kubectl
            defaultMode: 384
      containers:
        - name: rocky-ssh
          image: sjwayrhz/rocky-8.4:kubectl
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: ssh
              mountPath: "/root/.ssh/authorized_keys"
              subPath: authorized_keys
              readOnly: true
            - name: kubectl
              mountPath: "/root/.kube/config"
              subPath: config
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 22