
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: app-dev
  labels:
    app: redis
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
  - name: redis
    port: 6379
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: redis-access
  namespace: app-dev
  labels:
    app: redis
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  type: NodePort
  ports:
  - name: redis-access
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30378
