quay.io/prometheus-operator/prometheus-operator: docker.io/sjwayrhz/prometheus-operator
quay.io/prometheus/alertmanager: docker.io/sjwayrhz/alertmanager
quay.io/prometheus/node-exporter: docker.io/sjwayrhz/node-exporter
quay.io/prometheus/prometheus: docker.io/sjwayrhz/prometheus
quay.io/prometheus/blackbox-exporter: docker.io/sjwayrhz/blackbox-exporter
quay.io/brancz/kube-rbac-proxy: docker.io/sjwayrhz/kube-rbac-proxy
jimmidyson/configmap-reload: docker.io/sjwayrhz/configmap-reload
grafana/grafana: docker.io/sjwayrhz/grafana
k8s.gcr.io/kube-state-metrics/kube-state-metrics: docker.io/sjwayrhz/kube-state-metrics
k8s.gcr.io/prometheus-adapter/prometheus-adapter: docker.io/sjwayrhz/prometheus-adapter
quay.io/prometheus-operator/prometheus-config-reloader: docker.io/sjwayrhz/prometheus-config-reloader